# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Turnkey CLI"
  homepage ""
  version "0.1.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.0/tkcli_0.1.0_macOS_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "d6e8118ede63b16b59911cc2e1a15f9c14a92d378be31d0c17580e96dc445f14"

      def install
        bin.install "tkcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.0/tkcli_0.1.0_macOS_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "5d3e28843d946fc5eb68dc89dbc28e7717553efcb92dadead153ff6b7b99a0e1"

      def install
        bin.install "tkcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.0/tkcli_0.1.0_Linux_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "cfd6290b7137eeb4c0c8f151af721ac31d42e64ea3cf80d12fb4d0bba9d47eab"

      def install
        bin.install "tkcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.0/tkcli_0.1.0_Linux_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "04cc91cd4b3d5971a9b1900a0929a4c0f621d8449e5d4ba7b9e10c0422387bf7"

      def install
        bin.install "tkcli"
      end
    end
  end
end
