# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tk < Formula
  desc "Turnkey CLI"
  homepage ""
  version "0.1.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.1/tk_0.1.1_macOS_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "d30fcb0fdc4f721742d262f4798719308929e9547a5dc4fc79d8d4acd3c5bd1a"

      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.1/tk_0.1.1_macOS_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "4db62f5cf8433982bb47566301aed63d6026cdeacb3609dc5ab9c30eee5a3276"

      def install
        bin.install "tk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.1/tk_0.1.1_Linux_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "ba1f038729ebafc528545e70e2241bc8d62c6222d8f591a2d41244cb67644c93"

      def install
        bin.install "tk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.1.1/tk_0.1.1_Linux_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "451f6d3d0968b8dcb30672de524eeb6d2ad176fc0d0db05cfcb03ba29251a959"

      def install
        bin.install "tk"
      end
    end
  end
end
