# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turnkey < Formula
  desc "Turnkey CLI"
  homepage ""
  version "0.2.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.0/turnkey_0.2.0_macOS_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "0c97e5077d4cf36d79463da11f22343919d39bac07f57218479d4879e01d1273"

      def install
        bin.install "turnkey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.0/turnkey_0.2.0_macOS_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "aaaa4055bd354bb190ae9182a6ce79047d760cfedbe477d9a7d0e1c64ce1f419"

      def install
        bin.install "turnkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.0/turnkey_0.2.0_Linux_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "ee9db9d60b6b7c3a007ab5ca9b3e801e9021ab4e7a064c0348ae4bc49913223c"

      def install
        bin.install "turnkey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.0/turnkey_0.2.0_Linux_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "58749d3ce46753dd5ce2b61e7e0432d22b81af248db313ee1e61fb80cfc72ee7"

      def install
        bin.install "turnkey"
      end
    end
  end
end
