# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turnkey < Formula
  desc "Turnkey CLI"
  homepage ""
  version "0.2.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.1/turnkey_0.2.1_macOS_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "36de3ae0f0000bede534eb17ed3e8afbece40c97bd8b3044e5d3ffe817425be4"

      def install
        bin.install "turnkey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.1/turnkey_0.2.1_macOS_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "b140d000d6347b2d8115288829c65d392eadbe7d9cdb2c56299bf5b279adde7c"

      def install
        bin.install "turnkey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.1/turnkey_0.2.1_Linux_ARM64.tar.gz", using: CurlDownloadStrategy
      sha256 "68d6f2c6a56317877db8d32d8dff531e74e2298b7deb5e3f4ac8747b613afdca"

      def install
        bin.install "turnkey"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tkhq/tkcli/releases/download/v0.2.1/turnkey_0.2.1_Linux_64bit.tar.gz", using: CurlDownloadStrategy
      sha256 "e091a38b32633daa3e90212df407291e41edd194ba81ec4c0fe9686ef175bbfe"

      def install
        bin.install "turnkey"
      end
    end
  end
end
